# Базовый образ
FROM node:14.18.1

# Установка рабочей директории
WORKDIR /app

# Важно для кеширования слоев
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci --production
RUN npm install sequelize-cli
RUN npm install
RUN find node_modules -name '.bin' -type d -exec chmod 755 {} \;


COPY app/. .

EXPOSE 8080

# Запуск тестов при запуске контейнера
CMD ["npm test"]