version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: olgaztv/devops-for-programmers-project-74
    working_dir: /app
    command: bash -c 'sleep 3 && npm test'
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db


  db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: