version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '8080:8080'
    command: bash -c 'sleep 10 && npm start'
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.4.6
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile