version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: olgaztv/devops-for-programmers-project-74
    working_dir: /app
    command: sh -c "npm test && npm start"