version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: olgaztv/devops-for-programmers-project-74
    working_dir: /app
    command: sh -c "npm test && npm start"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}