name: CI/CD

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: ${{ secrets.DB_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        run: make ci

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: olgaztv/devops-for-programmers-project-74:latest